#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [1]:
import pandas as pd

In [2]:
import os
os.listdir('../data/')

['health_insurance_cross_sell_prediction.csv', 'supermarket_sales.csv']

In [4]:
data_sales = '../data/supermarket_sales.csv'
df = pd.read_csv(data_sales)
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [10]:
df.groupby('Branch')['gross income'].sum().sort_values(ascending=False)

Branch
C    5265.1765
A    5057.1605
B    5057.0320
Name: gross income, dtype: float64

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [17]:
df.groupby(['Branch', 'City'])['gross income'].sum().sort_values(ascending=False)

Branch  City
C       Naypyitaw    5265.1765
A       Yangon       5057.1605
B       Mandalay     5057.0320
Name: gross income, dtype: float64

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [23]:
invoices_by_category = pd.pivot_table(df, index='Branch', columns='Product line', values='Invoice ID', aggfunc="count")
invoices_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [42]:
max_value = invoices_by_category['Electronic accessories'].idxmax()
print (f'Hайбільше інвойсів із покупкою товарів категорії Electronic accessories має філіал магазину {max_value}')

Hайбільше інвойсів із покупкою товарів категорії Electronic accessories має філіал магазину A

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

**1. Чи впливає тип покупця на прибуток?**
   
Ми маємо два типи покупців Member і Normal. Нам потрібно дослідити, яким чином тип покупця впливає на продажі. Якщо покупці типу Member  дають нам більший прибуток, то тоді слід зосередитися на впровадженні різних програм для залучення нових Members. Це можуть бути якісь реферальні програми та додаткові бонуси для існуючих Members за залучення нових покупців, а також можна розробити систему бонусів та додаткових знижок для Members для стимулювання продажів та підтримання лояльності покупців.

In [44]:
df.groupby('Customer type')['gross income'].agg(["count", "mean", "sum"])

               count       mean       sum
Customer type
Member           501  15.609110  7820.164
Normal           499  15.148707  7559.205

**2. Чи впливає на прибуток стать покупців? Хто робить найбільше покупок чоловіки чи жінки? Які категорії товарів найчастіше купують?**

Відповідь на це питання допоможе нам проаналізувати, покращити та можливо змінити асортимент в магазинах, а також оптимізувати рекламу в залежності від уподобань покупців різної статі.

In [53]:
gender_cust = df.groupby(['Gender', 'Product line'])['gross income'].agg(["count", "mean", "sum"])
gender_cust.sort_values(by=['Gender','sum'],ascending=False)

                               count       mean        sum
Gender Product line
Male   Health and beauty          88  16.576165  1458.7025
       Electronic accessories     86  15.080570  1296.9290
       Sports and travel          78  16.207635  1264.1955
       Fashion accessories        82  13.860915  1136.5950
       Home and lifestyle         81  14.006488  1134.5255
       Food and beverages         84  13.023768  1093.9965
Female Food and beverages         90  17.550750  1579.5675
       Fashion accessories        96  15.097917  1449.4000
       Home and lifestyle         79  18.105411  1430.3275
       Sports and travel          88  15.462511  1360.7010
       Electronic accessories     84  15.363958  1290.5725
       Health and beauty          64  13.810258   883.8565

**3. Також можемо дослідити середній рейтинг наших магазинів в різних містах і яким чином він впливає на продажі.**

Рейтинг магазину показує нам рівень задоволеності клієнта та впливає на залучення нових клієнтів і утримання вже існуючих. Низькі рейтинги свідчать про проблеми в обслуговуванні, уникнути або позбутися яких нам дозволить аналіз задоволеності клієнтів та виявлення причин низьких оцінок.

In [77]:
df.groupby('City')['Rating'].mean().sort_values(ascending=False)

City
Naypyitaw    7.072866
Yangon       7.027059
Mandalay     6.818072
Name: Rating, dtype: float64